import { PrismaClient } from '@prisma/client'

export async function seedTrivia(prisma: PrismaClient) {
  console.log('  🧠 Seeding trivia questions...')

  const triviaQuestions = [
    {
      question: 'What year was the famous T206 Honus Wagner card produced?',
      optionA: '1909',
      optionB: '1915',
      optionC: '1901',
      optionD: '1920',
      correctAnswer: 'A',
      explanation: 'The T206 Honus Wagner was produced between 1909–1911 by the American Tobacco Company and is one of the most valuable cards ever.',
    },
    {
      question: 'What does PSA stand for in card grading?',
      optionA: 'Professional Sports Authenticator',
      optionB: 'Premium Sports Appraiser',
      optionC: 'Professional Slab Authority',
      optionD: 'Primary Sports Authentication',
      correctAnswer: 'A',
      explanation: 'PSA stands for Professional Sports Authenticator, the most well-known card grading service in the hobby.',
    },
    {
      question: 'What is the highest grade a card can receive from PSA?',
      optionA: 'PSA 9 Mint',
      optionB: 'PSA 10 Gem Mint',
      optionC: 'PSA 10 Pristine',
      optionD: 'PSA 10 Perfect',
      correctAnswer: 'B',
      explanation: 'PSA 10 Gem Mint is the highest grade on the standard PSA scale, indicating virtually perfect condition.',
    },
    {
      question: 'Which baseball player\'s 1952 Topps card is among the most valuable in the hobby?',
      optionA: 'Babe Ruth',
      optionB: 'Willie Mays',
      optionC: 'Mickey Mantle',
      optionD: 'Jackie Robinson',
      correctAnswer: 'C',
      explanation: 'The 1952 Topps Mickey Mantle #311 is one of the most iconic and valuable baseball cards ever produced.',
    },
    {
      question: 'Which company revolutionized the card industry by introducing premium cards with tamper-proof packaging in 1989?',
      optionA: 'Topps',
      optionB: 'Fleer',
      optionC: 'Score',
      optionD: 'Upper Deck',
      correctAnswer: 'D',
      explanation: 'Upper Deck debuted in 1989 with hologram-stamped, premium quality cards in tamper-proof foil packs, changing the industry forever.',
    },
    {
      question: 'What term describes a card that was printed with a manufacturing mistake?',
      optionA: 'Short Print',
      optionB: 'Error Card',
      optionC: 'Variation Card',
      optionD: 'Miscut Card',
      correctAnswer: 'B',
      explanation: 'An error card has a manufacturing mistake such as wrong stats, misspelled name, or wrong photo. Some become highly collectible.',
    },
    {
      question: 'What does "RC" on a card typically indicate?',
      optionA: 'Rare Collectible',
      optionB: 'Regular Card',
      optionC: 'Rookie Card',
      optionD: 'Reprint Classic',
      correctAnswer: 'C',
      explanation: 'RC stands for Rookie Card, indicating the player\'s first officially licensed card in a major set.',
    },
    {
      question: 'Which grading company uses a scale that goes up to 10 with half-point increments and is known for black labels?',
      optionA: 'PSA',
      optionB: 'BGS (Beckett)',
      optionC: 'SGC',
      optionD: 'CGC',
      correctAnswer: 'B',
      explanation: 'BGS (Beckett Grading Services) uses half-point increments and awards the coveted Black Label for a perfect 10 across all four sub-grades.',
    },
    {
      question: 'What is a "refractor" in card collecting?',
      optionA: 'A card with a holographic rainbow finish',
      optionB: 'A card made from recycled materials',
      optionC: 'A card that was refunded by the manufacturer',
      optionD: 'A card with raised lettering',
      correctAnswer: 'A',
      explanation: 'Refractors are a type of parallel card with a special chromium coating that creates a rainbow holographic effect when tilted.',
    },
    {
      question: 'What era of card collecting from the late 1980s to early 1990s is known for mass overproduction?',
      optionA: 'The Golden Age',
      optionB: 'The Junk Wax Era',
      optionC: 'The Chrome Age',
      optionD: 'The Vintage Period',
      correctAnswer: 'B',
      explanation: 'The Junk Wax Era (roughly 1987–1993) saw massive overproduction of cards, making most cards from this period worth very little today.',
    },
    {
      question: 'Which brand is most famous for prospect and minor league baseball cards?',
      optionA: 'Topps Heritage',
      optionB: 'Panini Prizm',
      optionC: 'Bowman',
      optionD: 'Donruss',
      correctAnswer: 'C',
      explanation: 'Bowman (especially Bowman Chrome) is the go-to brand for prospect and minor league cards, making them the first cards of future stars.',
    },
    {
      question: 'What does "SP" stand for in card collecting terminology?',
      optionA: 'Special Print',
      optionB: 'Short Print',
      optionC: 'Standard Parallel',
      optionD: 'Serial Pressed',
      correctAnswer: 'B',
      explanation: 'SP stands for Short Print, meaning the card was produced in lower quantities than the base set, making it harder to find.',
    },
    {
      question: 'What year did Topps produce its first baseball card set?',
      optionA: '1948',
      optionB: '1951',
      optionC: '1952',
      optionD: '1955',
      correctAnswer: 'B',
      explanation: 'While the iconic 1952 set is more famous, Topps actually produced its first baseball cards in 1951 with red and blue back variations.',
    },
    {
      question: 'Which Michael Jordan card is considered his most iconic rookie card?',
      optionA: '1986 Fleer #57',
      optionB: '1984 Star #101',
      optionC: '1987 Fleer #59',
      optionD: '1988 Fleer All-Star #120',
      correctAnswer: 'A',
      explanation: 'The 1986 Fleer #57 Michael Jordan is widely considered his most iconic and valuable mainstream rookie card.',
    },
    {
      question: 'What does "GU" mean when found on a card?',
      optionA: 'Gold Unlimited',
      optionB: 'Game Used',
      optionC: 'Graded Unverified',
      optionD: 'Guaranteed Unique',
      correctAnswer: 'B',
      explanation: 'GU stands for Game Used, indicating the card contains a piece of material (jersey, bat, etc.) actually used in a game.',
    },
    {
      question: 'Which company currently holds the exclusive MLB baseball card license?',
      optionA: 'Panini',
      optionB: 'Upper Deck',
      optionC: 'Topps (Fanatics)',
      optionD: 'Leaf',
      correctAnswer: 'C',
      explanation: 'Topps held the exclusive MLB license for years, and Fanatics acquired Topps to maintain the exclusive relationship with Major League Baseball.',
    },
    {
      question: 'What is a "1/1" card?',
      optionA: 'The first card in a set',
      optionB: 'A card that is the only one of its kind ever produced',
      optionC: 'A card graded as the best in existence',
      optionD: 'The first card pulled from a box',
      correctAnswer: 'B',
      explanation: 'A 1/1 (one of one) card means only a single copy was ever produced, making it the ultimate collector\'s item.',
    },
    {
      question: 'What is the term for a card that has been professionally encased in a hard plastic holder after grading?',
      optionA: 'Cased',
      optionB: 'Topped',
      optionC: 'Slabbed',
      optionD: 'Sealed',
      correctAnswer: 'C',
      explanation: 'When a card is graded and encased in a hard plastic holder, collectors call it "slabbed." The holder is known as a slab.',
    },
    {
      question: 'What does "BGS" stand for?',
      optionA: 'Best Grade Standard',
      optionB: 'Beckett Grading Services',
      optionC: 'Base Grade Score',
      optionD: 'Buyer\'s Guide Score',
      correctAnswer: 'B',
      explanation: 'BGS stands for Beckett Grading Services, one of the top card grading companies known for their sub-grade system.',
    },
    {
      question: 'Which of these is NOT a common sub-grade category used by BGS?',
      optionA: 'Centering',
      optionB: 'Corners',
      optionC: 'Color',
      optionD: 'Surface',
      correctAnswer: 'C',
      explanation: 'BGS evaluates four sub-grades: Centering, Corners, Edges, and Surface. Color is not one of the sub-grade categories.',
    },
    {
      question: 'What is a "hobby box" compared to a retail box?',
      optionA: 'A box with fewer packs but higher price',
      optionB: 'A box sold only at card shops/online with guaranteed hits',
      optionC: 'A box made for children only',
      optionD: 'A box with only vintage cards',
      correctAnswer: 'B',
      explanation: 'Hobby boxes are sold through card shops and online dealers, typically guaranteeing autographs or relic cards (hits) that retail boxes don\'t.',
    },
    {
      question: 'What does "numbered to /25" mean on a card?',
      optionA: 'It is card #25 in the set',
      optionB: 'Only 25 copies of that card exist',
      optionC: 'It costs $25',
      optionD: 'It was made in the 25th year of the brand',
      correctAnswer: 'B',
      explanation: 'When a card is "numbered to /25," it means only 25 copies were produced. Each card is individually stamped with its number (e.g., 13/25).',
    },
    {
      question: 'Which of these is considered the "Holy Grail" of basketball cards?',
      optionA: '2003 Topps LeBron James RC',
      optionB: '1986 Fleer Michael Jordan RC',
      optionC: '1996 Topps Chrome Kobe Bryant RC',
      optionD: '1969 Topps Lew Alcindor RC',
      correctAnswer: 'B',
      explanation: 'The 1986 Fleer Michael Jordan rookie card is widely considered the Holy Grail of basketball cards, commanding top prices in high grades.',
    },
    {
      question: 'What does "wax pack" originally refer to?',
      optionA: 'A pack sealed with wax paper wrapping',
      optionB: 'A pack containing wax figurines',
      optionC: 'A specially coated premium pack',
      optionD: 'A pack that smells like wax',
      correctAnswer: 'A',
      explanation: 'Wax packs got their name from the waxy paper wrapping used to seal card packs in the early days of the hobby.',
    },
    {
      question: 'What is the term for a card showing a player on a team different from the one listed?',
      optionA: 'Misprint',
      optionB: 'Traded variation',
      optionC: 'Photo variation',
      optionD: 'Error card',
      correctAnswer: 'C',
      explanation: 'A photo variation (or SP photo variation) shows an alternate image, sometimes depicting a player with a different team or in an unusual pose.',
    },
    {
      question: 'What is a "case hit" in card collecting?',
      optionA: 'When you drop a case on the ground',
      optionB: 'A rare card that appears roughly once per sealed case of boxes',
      optionC: 'The first card in every case',
      optionD: 'A damaged card from shipping',
      correctAnswer: 'B',
      explanation: 'A case hit is an extremely rare card that statistically appears only about once per sealed case (usually 12 hobby boxes).',
    },
    {
      question: 'Which card brand is known for the "Prizm" basketball product line?',
      optionA: 'Topps',
      optionB: 'Upper Deck',
      optionC: 'Panini',
      optionD: 'Bowman',
      correctAnswer: 'C',
      explanation: 'Panini produces the popular Prizm line, which has become one of the most sought-after basketball card products since its debut in 2012.',
    },
    {
      question: 'What is a "superfractor"?',
      optionA: 'A card with super gloss finish',
      optionB: 'A 1/1 gold-colored refractor parallel',
      optionC: 'The biggest card in a set',
      optionD: 'A factory-sealed card',
      correctAnswer: 'B',
      explanation: 'A superfractor is a 1/1 parallel with a distinctive gold chromium finish. Being the only copy makes it the ultimate chase card.',
    },
    {
      question: 'What year did Panini first produce NBA licensed cards?',
      optionA: '2005',
      optionB: '2009',
      optionC: '2012',
      optionD: '2015',
      correctAnswer: 'B',
      explanation: 'Panini became the exclusive NBA card manufacturer starting with the 2009-10 season after acquiring the license from Upper Deck.',
    },
    {
      question: 'What is "penny sleeving" a card?',
      optionA: 'Selling a card for a penny',
      optionB: 'Putting a card in a thin soft plastic sleeve for basic protection',
      optionC: 'Attaching a penny to a card for good luck',
      optionD: 'Grading a card as worthless',
      correctAnswer: 'B',
      explanation: 'Penny sleeving means placing a card in an inexpensive thin plastic sleeve (called a penny sleeve) as a first layer of protection.',
    },
    {
      question: 'Which set is considered the first modern era "super premium" baseball card product?',
      optionA: '1990 Leaf',
      optionB: '1993 Finest',
      optionC: '1989 Upper Deck',
      optionD: '1992 Bowman',
      correctAnswer: 'C',
      explanation: 'The 1989 Upper Deck set is widely considered the first super premium card product with its high-quality photography, stock, and anti-counterfeit hologram.',
    },
    {
      question: 'What does "patch card" refer to?',
      optionA: 'A card with a software update code',
      optionB: 'A card containing a piece of a jersey patch or logo',
      optionC: 'A card that has been repaired',
      optionD: 'A card from a patchwork set',
      correctAnswer: 'B',
      explanation: 'A patch card contains an actual piece of a jersey patch, team logo, or nameplate embedded in the card, making them more valuable than plain jersey swatches.',
    },
    {
      question: 'What is the "Topps Tiffany" set?',
      optionA: 'A set designed by the Tiffany jewelry company',
      optionB: 'A limited glossy version of the regular Topps set',
      optionC: 'A women\'s-only card set',
      optionD: 'An error-filled recall set',
      correctAnswer: 'B',
      explanation: 'Topps Tiffany sets are limited-edition glossy versions of the standard Topps base sets, produced in much smaller quantities and highly collectible.',
    },
    {
      question: 'How many cards are in a standard complete set of 1989 Upper Deck baseball?',
      optionA: '500',
      optionB: '660',
      optionC: '700',
      optionD: '800',
      correctAnswer: 'C',
      explanation: 'The 1989 Upper Deck baseball set contains 700 cards, highlighted by the Ken Griffey Jr. rookie card (#1).',
    },
    {
      question: 'What famous Ken Griffey Jr. card is card #1 in its set and one of the most iconic modern rookies?',
      optionA: '1989 Topps Traded',
      optionB: '1989 Upper Deck #1',
      optionC: '1989 Fleer #548',
      optionD: '1989 Donruss Rated Rookie',
      correctAnswer: 'B',
      explanation: 'The 1989 Upper Deck #1 Ken Griffey Jr. is one of the most recognizable and collected modern rookie cards in the hobby.',
    },
  ]

  for (let i = 0; i < triviaQuestions.length; i++) {
    const q = triviaQuestions[i]
    await prisma.triviaQuestion.upsert({
      where: { id: `trivia-${i + 1}` },
      update: {
        question: q.question,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
      },
      create: {
        id: `trivia-${i + 1}`,
        question: q.question,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        correctAnswer: q.correctAnswer,
        explanation: q.explanation,
      },
    })
  }

  console.log(`    ✅ Seeded ${triviaQuestions.length} trivia questions`)
}
